INSERT INTO `Polls` (`Description`, `Goal`, `Create_by`) VALUES('Encuesta para alumnos sobre la creación de una herramienta virtual para la calendarización de exámenes en la Universidad Martin Lutero sede Ocotal', 100, 'Hendell');
INSERT INTO `Polls` (`Description`, `Goal`, `Create_by`) VALUES('Encuesta para docentes sobre la creación de una herramienta virtual para la calendarización de exámenes en la Universidad Martin Lutero sede Ocotal', 10, 'Hendell');

INSERT INTO `Poll_Questions` (`Id_Poll`, `Id_Question`, `Body`) VALUES
(1, 1, '¿Te gustaría consultar los calendarios de exámenes online?'),
(1, 2, '¿Sabes cuando son los exámenes en el trimestre?'),
(1, 3, '¿Con que frecuencia te das cuenta de los calendarios de exámenes de la universidad?'),
(1, 4, '¿Tienes acceso a una computadora?'),
(1, 5, '¿Tienes acceso a internet?'),
(1, 6, '¿Cuántas horas hace uso de la computadora a diario? '),
(1, 7, '¿Te gustaría acceder desde tu celular a la calendarización de exámenes de la universidad?'),
(1, 8, '¿Qué nivel de conocimiento tienes en computación?'),
(1, 9, '¿Te preparas de antemano para los exámenes?'),
(1, 10, '¿Qué formato prefieres en los calendarios; físico o digital?');

INSERT INTO `Poll_Questions` (`Id_Poll`, `Id_Question`, `Body`) VALUES
(2, 1, '¿Te gustaría consultar los calendarios de exámenes online?'),
(2, 2, '¿Sabes cuando son los exámenes en el trimestre?'), 
(2, 3, '¿Con que frecuencia te enteras de los calendarios de exámenes de la universidad?'),
(2, 4, '¿Tienes acceso a una computadora?'),
(2, 5, '¿Tienes acceso a internet?'),
(2, 6, '¿Cuántas horas hace uso de la computadora a diario? '),
(2, 7, '¿Qué nivel de conocimiento tienes en computación?'),
(2, 8, '¿Qué formato prefieres en los calendarios; físico o digital?'),
(2, 9, '¿Te gustaría que los estudiantes puedan revisar sus calendarios de exámenes de manera online?');

INSERT INTO `Poll_Questions_Options` (`Id_Poll`, `Id_Question`, `Id_Option`, `Value`) VALUES
(1, 1, 1, 'Si'),
(1, 1, 2, 'No'),
(1, 2, 1, 'Si'),
(1, 2, 2, 'No'),
(1, 2, 3, 'Lo ignoro'),
(1, 3, 1, 'Mensual'),
(1, 3, 2, 'Semanal'),
(1, 3, 3, 'Trimestral'),
(1, 3, 4, 'Ninguno'),
(1, 4, 1, 'Si'),
(1, 4, 2, 'No'),
(1, 5, 1, 'Si'),
(1, 5, 2, 'No'),
(1, 6, 1, 'Menos de una hora'),
(1, 6, 2, 'Mas de dos horas'),
(1, 6, 3, 'Mas de cuatro horas'),
(1, 6, 4, 'No la uso'),
(1, 7, 1, 'Si'),
(1, 7, 2, 'No'),
(1, 8, 1, 'Alto'),
(1, 8, 2, 'Medio'),
(1, 8, 3, 'Bajo'),
(1, 8, 4, 'Ninguno'),
(1, 9, 1, 'Si'),
(1, 9, 2, 'No'),
(1, 10, 1, 'Fisico'),
(1, 10, 2, 'Digital');

INSERT INTO `Poll_Questions_Options` (`Id_Poll`, `Id_Question`, `Id_Option`, `Value`) VALUES
(2, 1, 1, 'Si'),
(2, 1, 2, 'No'),
(2, 2, 1, 'Si'),
(2, 2, 2, 'No'),
(2, 2, 3, 'Lo ignoro'),
(2, 3, 1, 'Anual'),
(2, 3, 2, 'Mensual'),
(2, 3, 3, 'Semanal'),
(2, 3, 4, 'Trimestral'),
(2, 3, 5, 'Ninguno'),
(2, 4, 1, 'Si'),
(2, 4, 2, 'No'),
(2, 5, 1, 'Si'),
(2, 5, 2, 'No'),
(2, 6, 1, 'Menos de una hora'),
(2, 6, 2, 'Mas de dos horas'),
(2, 6, 3, 'Mas de cuatro horas'),
(2, 6, 4, 'No la uso'),
(2, 7, 1, 'Alto'),
(2, 7, 2, 'Medio'),
(2, 7, 3, 'Bajo'),
(2, 7, 4, 'Ninguno'),
(2, 8, 1, 'Fisico'),
(2, 8, 2, 'Digital'),
(2, 9, 1, 'Si'),
(2, 9, 2, 'No');